
s='GTGACCTTCTTCCGCTCGCCCCATAATGGGTCGTATCGGGAGGCTACGTTTAATATCGTACATAGTTGACCTAGGATAGGCCCTCGTTGCGAGGAAGAGTTAAGGCATTAAAGTAATCTATCTGCTAAACAGCCATTTGATTCCACTAAGAAAAGCGAGCCATCCGTTTCCAAGGCTCAACGGTGGAAAGTTTCTTAAAAACTAGAGATAGTCACACCACGTAAGCGTGATCAGGATTACCCACGGACAACCGTGCCGTTGTTTATATTTGGTGGTTGGGGCAGAGCTCCCAGGACTGTGTAACTCGGAATGCCAGCGAAGCGGATGTTCTGCATCCTTCGTTACGTGCGACGGAGTATAGCCTTCCCGTGCGACGCTGCGCCCAAACCATAGGTTTCCGTATGGCCTGCGTTAAAGTCGTGAACAACATTTCCTGCTACACGGTCAGTTCTAGACCGTGTATTGAGCCTAAATGTATATGAGACAAAATTTCTATTCACAGCGTGCCCGAGGCAGCTCGACACCGCATCTAATTGGTATCGGTGTCTTAGAAAAGGCCAATTCTCGCACTGGCTCAAAAAGTGTAATTTCGGCCCGTCCTATTCACTAAAGTCTCTTGAATCGTCAAAACCAAATTTTATCCGCCGTGAGCACGTTGAATGCCTTCACTGCCCCCAGCGCAGTTAACCTGGCAAGTGAACTCTATATACAGAACAGCAGCCCGAGTTTAACCCATAACACCAAAGAGTCGTGCTCTGCCCCCGATGTAATAGAGTAGAGGAACCTACATAAGATTCACTCGGTGAACCGCATTTGCACCTCCTAAAGATAAGTTATCCTGTTCATTCCTGCGGTAGGCCTCGTGAAGGAACTGCCGTCTATCTCATAGAGGCTTCACAAGCGTGACTGCAAAAGTATTAATGATCATCCGACCACGTGATGACCCTCCGCCCTATCGAACGACTTGCACCCGTGCTCGGATCCGGC'
a='A'
c='C'
g='G'
t='T'
i=0
j=0
z=''
licznik_a=0
licznik_c=0
licznik_g=0
licznik_t=0
for i in range(len(s)):
    z=z+s[i]+' '
r=z.split()
#print r
for j in range(len(r)):
    if r[j]==a:
        licznik_a=licznik_a+1
    elif r[j]==c:
        licznik_c=licznik_c+1
    elif r[j]==g:
        licznik_g=licznik_g+1
    elif r[j]==t:
        licznik_t=licznik_t+1
print str(licznik_a)+' '+str(licznik_c)+' '+str(licznik_g)+' '+str(licznik_t)

   


        
    

    
