s='CCCCTTTTGCCCGTTCCTGGTAACACTTGCGCATCTACGGGAGGATGAAGTGATCATAGATATCTGTACACCGGGGTGGGCCCAATTCGCTTATCTGAGATATAGATCCAGTGCCACAGGTCAGTATTAATCGGGTGACCGTCCGACAGTGGACCTATGCTCCTGGGGAAGGCTGAATTATGTCTCTCGATAGAGAGTATCTTGCGTGGCACGTTTGAGGACAAATCGGAAGCCCGGAGCTCCAACCCACCGAAATTAATGCGGAAGCTACTGTATCAGCATAGAATGACAGCGACATGCTAACCCTCTAGGGCTTTTTCTCGAAGAGTTAGCGGTTGCCAGGATCCCAGCAGACCCACGATTAGTAGTGGGTAATAATCCGGTAACAGAGCTCAAATATACGCTGTACCGTGTCTACCCGTAAGCGATGACCGACGCTAACACTCCCAGAGGCGCACAAATATATAAGGACGCCACGTGCTCACAACATGCGAAAGGACGACCATGCCTCGTACCCTGCTATCTTGCGGTATTCTCTCTATAGTAGCCACCTCGCATCGCCGTCCATCTCCCATCGGTGCTGAGTTGCTAAGTTCCCATAGCTCACCAATTAAGTTATGGCGCCTTAACCTATGAGACATTGCATGGCACCGTGTTAAGGTCGAGTCCCCGTGACACTTGGCAACTCGTTGCCCGCTTAAGATGAATACATGAGCCGTATTGGCTGCACAAAAAACTAAAACCGAGATCGAACCGCTTTTGAGTGGTAGACCACCATGGCGTGCTAGGTCTGCCACCCGAGTGCAATACTGGTGCATCCTTGATGTGTCATCCCAATGCCGGGGGTAGGGTATCTTGCACACCCGTCGATATGATTCGCTCACATACTTGGCTCATCTCCAGTCCAATGCGAGCCGCGGTCAACCCAGTTGCGATCAG'
a='A'
c='C'
g='G'
t='T'
u='U'
i=0
j=0
k=0
z=''
rna=''
for i in range(len(s)):
    z=z+s[i]+' '
r=z.split()
for j in range(len(r)):
    if r[j]==t:
        r[j]=u
for k in range(len(r)):
    rna=rna+r[k]
print rna
