sc='TTTGACTGCGACGAGACGTGCGCGACGACGTGTTTAACTCGGAGGAGACGATGACGCTGCAGCGCGACCTCCACGGTCCTCGAGCGAGTGTGCGGAAGGGTCGCTGCACATCGAATCCAGGCACCTGTCAATGTTAGGGCTCTACTACACCGTTCGATATAGCCCCAGTAACCTATTACTCAAATGTTGTGGTCATAACTCATGCTGTACGCAGATGAATACCTATCTACATCCCAGGATCCGCCGCCGGAGAAAGGGGATGATTAGAGAAATAGGCACACCTGGTTCTCCCTCTAGCGAGACTCGATAAAGGTCGGGACTGAGCTGTGAGCGGCGTTGCCAACAGGGTATTTCTGCCGTGATAGGGACCAAACGTCAATAAAGCAAGGTTTGAGCTCGCGCCACCTGGCCGTTTCATTTTCCACTGTATTCAGGCGCGCTAAGCGGACCGGGGGACTCAATAACCGTATTGAGGTAATGACTCCACCCTACTGACTAGACTCAACTACAGAGCCATTAAAAACCCGTCCGGACCTGCCTAGGTAAATAGGGTGCATACGGTCGATAGGATAGACCGGCGTGAGGGATACTGTTTTCTGGCGGAGATCAGACAAGGGAAAGTCCAGTCTTCGAACCCGAACCACCCGCGCCCAGAAATCATTCGGAGCCAACGGTGCATCGTTTACACTGCACCATTGCATGGTGCGCGTTCACGCTAATGGAATCGCAAACTTACTTGCTTACTTTGACAGTGATGGCTAGGTAATCATAATCATTGCACATCTTAAGGCCACGGCACTTGCTTTAGATATTCGAGGTGTGTCCATAACCTTACTACATACTCAGAACTCATCTGATGAC'
a='A'
c='C'
g='G'
t='T'
i=0
j=0
k=0
l=0
m=0
z=''
u=''
s=''

l=len(sc)-1
for i in range(len(sc)):
    u=u+sc[l-i]
for k in range(len(u)):
    z=z+u[k]+' '
r=z.split()

for j in range(len(r)):
    if r[j]==a:
        r[j]=t
    elif r[j]==t:
        r[j]=a
    elif r[j]==g:
        r[j]=c
    elif r[j]==c:
        r[j]=g
for l in range(len(r)):
    s=s+r[l]
print s


